### ISSUE TITLE
Rewrite CEF Event

### ISSUE THREAD

**Issue by kamushadenes** [kamushadenes/cefevent#11]
This is an old project, in need of some refactoring.

What do you folks think about having it rewritten in Go? 

My arguments:

- Easier deployment in restricted environments (only a single binary), as was usually the case when I consulted ArcSight
- Better data assertion with types
- Better (although uglier) error handling
- Likely a higher EPS thoughput with the use of goroutines and channels
- I like Go :D

@tristanlatr
@pcktdmp
@urbantom
@lewisoaten

**Comment by pcktdmp** [comment]
Inspired by your repo I already made a Go module for this a while back: https://github.com/pcktdmp/cef :-)
Although this is only code to generate the event it can be the base of an event emitter to send to for instance syslog.

**Comment by tristanlatr** [comment]
I think you should keep the python implementation active. It looks like a lot of projects uses this library.

**Comment by pcktdmp** [comment]
Yes indeed, projects are using this actively. I would like to volunteer as co-maintainer :)

**Comment by kamushadenes** [comment]
@pcktdmp just invited you :)
