### ISSUE TITLE
Data CEF

### ISSUE THREAD

**Issue by steevivo** [kamushadenes/cefevent#13]
Hi all,

Could you tell me if you introduce random data in your generator CEF ?

Thx

**Comment by kamushadenes** [comment]
I didn't, but can do.

I'll likely add that on https://github.com/kamushadenes/cefevent-go when I get some time, and will port it here to.

If you're feeling inclined, feel free to open a PR :)

**Comment by pcktdmp** [comment]
@steevivo could you tell me what your use case is?

**Comment by kamushadenes** [comment]
Hello @steevivo

This feature just landed :)

Please see https://github.com/kamushadenes/cefevent#event-generation
