### ISSUE TITLE
flexString fields

### ISSUE THREAD

**Issue by 1lyasam** [kamushadenes/cefevent#9]
Hi Kamus, thanks for this wonderful classs.
I noticed an Issue on flex fields i saw is that flexString1 should be decoded to "flexString1" in CEF and not to "fs1".
maybe it used to be like this in the past but now it not working.

**Comment by kamushadenes** [comment]
Hi @1lyasam , I'm terrible sorry, as I wasn't watching this repository.

Can you please give your thoughts on #11 ?
